services:
  jenkins:
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .Renviron
    image: pkinif/jenkins:latest
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home